### ISSUE TITLE
Question about CPU clock

### ISSUE THREAD

**Issue by rajolm** [giodani97/Lenovo-E560-OpenCore#1]
Hi @giodani97 
Thank you very much for sharing your OpenCore config with us
rsdev69 did changes to CPU frequency in his clover configurations and he have Core i3 CPU which doesn't have Turbo Boost

here is the specs of Core i5 CPU:

![image](https://user-images.githubusercontent.com/61861362/76697899-59c5e580-66a5-11ea-9d8f-d00147a4e465.png)

Notice how Max Turbo Frequency and TPD have differences from you Core i3 CPU specs:
 
![image](https://user-images.githubusercontent.com/61861362/76697920-8d087480-66a5-11ea-81eb-392d2cb3a40b.png)

1. I think you have the Core i5 CPU like me, so I want to ask if your OpenCore configurations CPU frequency for the Core i5 CPU? and Does Turbo Boost work with your configurations?
2. Does the sleep work with your OpenCore configurations (I think the configurations must disable the dGPU)
3. Can you please keep your Repo updated, so we can switch to it instead of using rsdev69 clover config?

**Comment by giodani97** [comment]
Hi @rajolm, sorry but in the last two weeks I had to take the last exams and to discuss my thesis. I fixed the sleeping problem (the discrete graphic card was in fact not disabled). In the next hour I'll upload the updated configuration. For the CPU I have an Intel core i5 6200u like you. As far as I know OpenCore doesn't handle the CPU so we don't have to configure it. You can download [Intel Power Gadget](https://software.intel.com/en-us/articles/intel-power-gadget) and run it to see the stats of your cpu. Here are the stats of my CPU under stress
![My cpu under stress](https://user-images.githubusercontent.com/43290286/76840108-ed7aeb80-6836-11ea-97eb-c6bc66bdbe90.png). 
As you can see the max frequency is 2,8 Ghz.

**Comment by rajolm** [comment]
> Hi @rajolm, sorry but in the last two weeks I had to take the last exams and to discuss my thesis. I fixed the sleeping problem (the discrete graphic card was in fact not disabled). In the next hour I'll upload the updated configuration. For the CPU I have an Intel core i5 6200u like you. As far as I know OpenCore doesn't handle the CPU so we don't have to configure it. You can download [Intel Power Gadget](https://software.intel.com/en-us/articles/intel-power-gadget) and run it to see the stats of your cpu. Here are the stats of my CPU under stress
> ![My cpu under stress](https://user-images.githubusercontent.com/43290286/76840108-ed7aeb80-6836-11ea-97eb-c6bc66bdbe90.png).
> As you can see the max frequency is 2,8 Ghz.

@giodani97 Thank you so much for the info and for updating your configurations, you are awesome!
I want to point out that fixing sleep with `-wegnoegpu` boot flag will cause another problem which is reduce the screen brightness of the laptop screen, I tried it my self and it is noticeable clearly, the screen brightness drastically get reduced

please check these links it have a better solution to disable discrete graphic card using SSDT:

https://www.tonymacx86.com/threads/maximum-brightness-gets-reduced-by-using-wegnoegpu.288969/

https://www.tonymacx86.com/threads/guide-disabling-discrete-graphics-in-dual-gpu-laptops.163772/#post-1036521

https://osxlatitude.com/forums/topic/12660-maximum-brightness-gets-reduced-by-using-wegnoegpu/

It will be very nice if you can fix the sleep issue correctly and keep this repo updated, It will be the best configurations Repo for all the E560 Hackintosh users

Thank you very much and best wishes

**Comment by giodani97** [comment]
Didn't know that wegnoegpu affected max brightness. I updated the repo fixing bluetooth and camera by mapping USB ports. Sleep should work properly now. Also dumped and patched DSDT myself as the old one caused the error "ACPI: executed x blocks of module-level executable AML code". Try it out and let me know if there are any errors by opening a new issue.
